# Generated by Django 4.0.6 on 2022-09-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('size', models.CharField(max_length=120)),
                ('prices', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
    ]
